### ISSUE TITLE
只使用弹框和下载功能，检查更新自己实现的

### ISSUE THREAD

**Issue by liu-xinhui** [xwdz/QuietVersion#2]
有办法使用这个库吗

**Comment by xwdz** [comment]
可以的.自己定义检查更新的逻辑即可 [simple](https://github.com/xwdz/QuietVersion/blob/master/lib/src/main/java/com/xwdz/version/strategy/CheckUpgradeStrategy.java)

**Comment by liunewshine** [comment]
我是想自己setDownloadUrl
